server:
  port: 8002
spring:
  application:
    name: provider-ticker

eureka:
  prefer-ip-address: true #注册服务的时候使用服务的ip地址
  instance-id: provider-ticker
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


